# permissions for end users to view accesspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accesspolicy-viewer-role
rules:
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - accesspolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - accesspolicies/status
  verbs:
  - get
