# permissions for end users to view ingressgatewaydeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressgatewaydeployment-viewer-role
rules:
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - ingressgatewaydeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - ingressgatewaydeployments/status
  verbs:
  - get
