# permissions for end users to view ingressgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressgateway-viewer-role
rules:
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - ingressgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - ingressgateways/status
  verbs:
  - get
