# permissions for end users to edit ingressgatewaydeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressgatewaydeployment-editor-role
rules:
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - ingressgatewaydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - ingressgatewaydeployments/status
  verbs:
  - get
