# permissions for end users to edit ingressgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressgateway-editor-role
rules:
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - ingressgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - ingressgateways/status
  verbs:
  - get
