# permissions for end users to view virtualdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualdeployment-viewer-role
rules:
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - virtualdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - virtualdeployments/status
  verbs:
  - get
