# permissions for end users to edit virtualdeploymentbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualdeploymentbinding-editor-role
rules:
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - virtualdeploymentbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - virtualdeploymentbindings/status
  verbs:
  - get
