# permissions for end users to edit virtualdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualdeployment-editor-role
rules:
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - virtualdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - virtualdeployments/status
  verbs:
  - get
