# permissions for end users to view virtualserviceroutetables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualserviceroutetable-viewer-role
rules:
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - virtualserviceroutetables
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - virtualserviceroutetables/status
  verbs:
  - get
