# permissions for end users to view virtualdeploymentbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualdeploymentbinding-viewer-role
rules:
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - virtualdeploymentbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - virtualdeploymentbindings/status
  verbs:
  - get
