# permissions for end users to edit virtualserviceroutetables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualserviceroutetable-editor-role
rules:
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - virtualserviceroutetables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicemesh.oci.oracle.com
  resources:
  - virtualserviceroutetables/status
  verbs:
  - get
