#
# Copyright (c) 2022, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: servicemesh.oci.oracle.com/v1beta1
kind: VirtualDeploymentBinding
metadata:
  name: productpage-version1-binding
  namespace: bookinfo-demo
spec:
  virtualDeployment:
    ref:
      name: productpage-version1
  target:
    service:
      ref:
        name: productpage
        namespace: bookinfo
      matchLabels:
        version: v1
